name: GETFIX_ADMIN_PDN_CI 

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish-artifact:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run build:prod-all
    - name: Copy the Configuration files
      run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"          
    - name: Archive build [production-page]
      if: success()
      uses: actions/upload-artifact@v2.2.3 
      with:
        name: deploy_main_page
        path: dist/
        retention-days: 2
